# Generated by Django 2.1.5 on 2019-02-25 01:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_shortcut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seq2seqDocument',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('server.document',),
        ),
        migrations.CreateModel(
            name='Seq2seqProject',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('server.project',),
        ),
        migrations.CreateModel(
            name='SequenceLabelingDocument',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('server.document',),
        ),
        migrations.CreateModel(
            name='SequenceLabelingProject',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('server.project',),
        ),
        migrations.CreateModel(
            name='TextClassificationDocument',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('server.document',),
        ),
        migrations.CreateModel(
            name='TextClassificationProject',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('server.project',),
        ),
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documentannotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentannotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='label',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seq2seqannotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seq2seqannotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sequenceannotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequenceannotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='documentannotation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_annotations', to='server.TextClassificationDocument'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seq2seqannotation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seq2seq_annotations', to='server.Seq2seqDocument'),
        ),
        migrations.AlterField(
            model_name='sequenceannotation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seq_annotations', to='server.SequenceLabelingDocument'),
        ),
    ]
