# Generated by Django 2.1.7 on 2019-02-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_shortcut'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='external_id',
            field=models.CharField(db_index=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
