# Generated by Django 2.1.3 on 2019-02-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_document_created_updated'),
        ('server', '0004_label_comment'),
    ]

    operations = [
    ]
