# Generated by Django 2.1.7 on 2019-03-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20190306_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='metadata',
            new_name='meta',
        ),
    ]
