# Generated by Django 2.1.5 on 2019-02-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_label_comment'),
        ('server', '0004_document_created_updated'),
    ]

    operations = [
    ]
