# Generated by Django 2.1.5 on 2019-02-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_merge_20190216_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentannotation',
            name='prob',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='seq2seqannotation',
            name='prob',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sequenceannotation',
            name='prob',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
