# Generated by Django 2.1.3 on 2019-02-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20190216_1121'),
        ('server', '0005_merge_20190214_1431'),
    ]

    operations = [
    ]
