# Generated by Django 2.1.5 on 2019-02-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_merge_20190217_1009'),
        ('server', '0005_merge_20190215_1429'),
    ]

    operations = [
    ]
