# Generated by Django 2.1.5 on 2019-02-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_merge_20190219_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='use_machine_model_sort',
            field=models.BooleanField(default=False),
        ),
    ]
