# Generated by Django 2.1.5 on 2019-03-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_project_use_machine_model_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
