# Generated by Django 2.1.5 on 2019-03-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_mlm_labels_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmlmannotation',
            name='manual',
        ),
        migrations.RemoveField(
            model_name='documentmlmannotation',
            name='user',
        ),
    ]
