# Generated by Django 2.1.5 on 2019-03-04 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_mlm_labels_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentGoldAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob', models.FloatField(blank=True, default=None, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_gold_annotations', to='server.Document')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Label')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='documentgoldannotation',
            unique_together={('document', 'label')},
        ),
    ]
