# Generated by Django 2.1.5 on 2019-06-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_auto_20190514_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('DocumentClassification', 'document classification'), ('SequenceLabeling', 'sequence labeling'), ('Seq2seq', 'sequence to sequence'), ('ImageClassification', 'image classification'), ('ImageCaptioning', 'image captioning')], max_length=30),
        ),
    ]
