# Generated by Django 2.1.5 on 2019-06-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_auto_20190625_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='shuffle_documents',
            field=models.BooleanField(default=False),
        ),
    ]
