# Generated by Django 3.1.7 on 2021-04-13 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20210411_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.FilePathField(default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='annotations_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
