# Generated by Django 3.2.4 on 2021-10-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_examplestate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="example",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="label",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="sequencelabelingproject",
            name="allow_overlapping",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sequencelabelingproject",
            name="grapheme_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="autolabelingconfig",
            name="label_mapping",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="example",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="example",
            name="filename",
            field=models.FileField(default=".", max_length=1024, upload_to=""),
        ),
        migrations.AlterField(
            model_name="label",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="label",
            name="text",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
