# Generated by Django 3.2.8 on 2021-11-08 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211018_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
