# Generated by Django 3.2.8 on 2021-11-02 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211018_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
