# Generated by Django 3.2.8 on 2021-11-17 05:56

from django.db import migrations, models

from label_types.models import generate_random_hex_color


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_example_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="background_color",
            field=models.CharField(default=generate_random_hex_color, max_length=7),
        ),
    ]
