# Generated by Django 3.2.8 on 2021-11-24 05:06

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_label_background_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='span',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='span',
            constraint=models.CheckConstraint(check=models.Q(('start_offset__gte', 0)), name='startOffset >= 0'),
        ),
        migrations.AddConstraint(
            model_name='span',
            constraint=models.CheckConstraint(check=models.Q(('end_offset__gte', 0)), name='endOffset >= 0'),
        ),
        migrations.AddConstraint(
            model_name='span',
            constraint=models.CheckConstraint(check=models.Q(('start_offset__lt', django.db.models.expressions.F('end_offset'))), name='start < end'),
        ),
    ]
