# Generated by Django 3.2.8 on 2021-12-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20211124_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='task_type',
            field=models.CharField(choices=[('Category', 'Category'), ('Span', 'Span'), ('Relation', 'Relation')], default='Category', max_length=30),
        ),
    ]
