# Generated by Django 3.2.8 on 2021-12-20 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20211124_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('label_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.label')),
            ],
            bases=('api.label',),
        ),
        migrations.CreateModel(
            name='SpanType',
            fields=[
                ('label_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.label')),
            ],
            bases=('api.label',),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('project', 'text'), name='unique_label'),
        ),
    ]
