# Generated by Django 3.2.8 on 2021-12-21 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20211220_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='label_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuga', to='api.doctype'),
        ),
        migrations.AddField(
            model_name='span',
            name='label_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoge', to='api.spantype'),
        ),
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.label'),
        ),
        migrations.AlterField(
            model_name='span',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.label'),
        ),
    ]
