# Generated by Django 3.2.8 on 2022-01-07 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_auto_20220107_0158"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Label",
        ),
    ]
