# Generated by Django 3.2.11 on 2022-01-28 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_auto_20220128_0246"),
        ("labels", "0004_auto_20220128_0246"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Example",
                ),
                migrations.DeleteModel(
                    name="ExampleState",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(name="Example", table="examples_example"),
                migrations.AlterModelTable(name="ExampleState", table="examples_examplestate"),
            ],
        )
    ]
