version: "3"
services:

  django:
    image: python:3.6
    volumes:
      - .:/src
      - venv:/src/venv
    command: ["/src/tools/dev-django.sh", "0.0.0.0:8000"]
    environment:
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "password"
      ADMIN_EMAIL: "admin@example.com"
      DATABASE_URL: "postgres://doccano:doccano@postgres:5432/doccano?sslmode=disable"
      ALLOW_SIGNUP: "False" 
    ports:
      - 8000:8800

  webpack:
    image: node:8
    volumes:
      - .:/src
      - node_modules:/src/app/server/static/node_modules
    command: ["/src/tools/dev-webpack.sh"]
    environment:
      WEBPACK_HOST: "0.0.0.0"
      WEBPACK_PORT: "8080"
      WEBPACK_POLL_MILLIS: "1000"
    ports:
      - 8080:8080

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: "doccano"
      POSTGRES_PASSWORD: "doccano"
      POSTGRES_DB: "doccano"
    volumes:
      - ./postgres/config:/etc/postgresql
      - ./postgres/log:/var/log/postgresql/
      - ./postgres/data:/var/lib/postgresql/data/

    ports:
      - "127.0.0.1:5432:5432"

volumes:
  node_modules:
  venv:
