version: "3"
services:
  webpack:
    image: node:8
    container_name: webpack
    volumes:
      - .:/src
      - node_modules:/src/app/server/static/node_modules
    command: ["/src/tools/dev-webpack.sh"]
    environment:
      WEBPACK_HOST: "0.0.0.0"
      WEBPACK_PORT: "8080"
      WEBPACK_POLL_MILLIS: "1000"
    ports:
      - 8080:8080

  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
      POSTGRES_USER: "doccano"
      POSTGRES_PASSWORD: "doccano"
      POSTGRES_DB: "doccano"
    ports:
      - 5432:5432

volumes:
  node_modules:
  venv:
