# Project information
site_name: 'doccano'
site_description: 'A Text Annotation tool for Humans'
site_author: 'Hiroki Nakayama'
site_url: 'https://doccano.github.io/doccano/'

# Repository
repo_name: 'doccano/doccano'
repo_url: 'https://github.com/doccano/doccano'

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Hiroki Nakayama'

theme:
  name: 'material'
  palette:
    primary: 'cyan'
    accent: 'cyan'
  show_sidebar: true

extra:
  social:
    - type: 'github'
      link: 'https://github.com/Hironsan'
    - type: 'twitter'
      link: 'https://twitter.com/Hironsan13'

# Page tree
nav:
  - Doccano: index.md
  - Getting started: getting-started.md
  - Tutorial: tutorial.md
  - Project Structure: project_structure.md
  - Advanced:
    - AWS HTTPS settings: advanced/aws_https_settings.md
    - OAuth2 settings: advanced/oauth2_settings.md
  #- Release notes: release-notes.md
  #- Author's notes: authors-notes.md
  - FAQ: faq.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - Roadmap: roadmap.md
