# Generated by Django 4.2.15 on 2025-06-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_project_allow_member_to_create_label_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="label_discrepancy_threshold",
            field=models.FloatField(default=0.0, help_text="Percentagem mínima de discrepância de labels (0-100)"),
        ),
    ]
