# Generated by Django 4.2.15 on 2025-06-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_project_label_discrepancy_threshold"),
        ("projects", "0009_question_questionoption_answer"),
    ]

    operations = []
