# Generated by Django 4.2.15 on 2025-06-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_question_data_type_noop"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="data_type",
            field=models.CharField(
                blank=True, choices=[("string", "String"), ("integer", "Integer")], max_length=10, null=True
            ),
        ),
    ]
