# Generated by Django 4.2.19 on 2025-07-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_current_version_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectversion',
            name='example_ids',
            field=models.JSONField(blank=True, default=list, help_text='IDs dos exemplos que devem ser mostrados nesta versão'),
        ),
    ]
