# Generated by Django 4.2.13 on 2025-01-07 00:00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projectversion_example_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectversion',
            name='examples_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ] 