# Generated by Django 4.2.19 on 2025-07-05 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0014_projectversion_example_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectversion',
            options={'ordering': ['version']},
        ),
        migrations.AddField(
            model_name='projectversion',
            name='examples_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='projectversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectversion',
            name='example_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
