# Generated by Django 4.2.19 on 2025-07-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_add_examples_snapshot'),
        ('projects', '0015_projectversion_examples_snapshot'),
    ]

    operations = [
    ]
