# Generated by Django 3.2.3 on 2021-05-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_annotations_relations_20210421_1445"),
        ("api", "0012_auto_20210514_0654"),
    ]

    operations = []
