# Generated by Django 3.2.3 on 2021-06-03 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0013_merge_20210528_1016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationrelations",
            name="timestamp",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="annotationrelations",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="annotation_relations", to="api.relationtypes"
            ),
        ),
        migrations.AlterField(
            model_name="annotationrelations",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_relations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="relationtypes",
            name="color",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="relationtypes",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name="annotationrelations",
            unique_together={("annotation_id_1", "annotation_id_2", "type", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="relationtypes",
            unique_together={("color", "name")},
        ),
    ]
