# Generated by Django 3.2.8 on 2021-12-21 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_auto_20211221_1430"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="new_label",
        ),
        migrations.RemoveField(
            model_name="span",
            name="new_label",
        ),
        migrations.AlterField(
            model_name="category",
            name="label",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.categorytype"),
        ),
        migrations.AlterField(
            model_name="span",
            name="label",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.spantype"),
        ),
    ]
