# Generated by Django 3.2.8 on 2021-12-22 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_auto_20220107_0200"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntentDetectionAndSlotFillingProject",
            fields=[
                (
                    "project_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("api.project",),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("DocumentClassification", "document classification"),
                    ("SequenceLabeling", "sequence labeling"),
                    ("Seq2seq", "sequence to sequence"),
                    ("IntentDetectionAndSlotFilling", "intent detection and slot filling"),
                    ("Speech2text", "speech to text"),
                    ("ImageClassification", "image classification"),
                ],
                max_length=30,
            ),
        ),
    ]
