# Generated by Django 3.2.8 on 2022-01-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_auto_20211222_0454"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="rolemapping",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="rolemapping",
                    name="project",
                ),
                migrations.RemoveField(
                    model_name="rolemapping",
                    name="role",
                ),
                migrations.RemoveField(
                    model_name="rolemapping",
                    name="user",
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Role",
                ),
                migrations.DeleteModel(
                    name="RoleMapping",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(name="Role", table="roles_role"),
                migrations.AlterModelTable(name="RoleMapping", table="roles_rolemapping"),
            ],
        ),
    ]
