# Generated by Django 3.2.11 on 2022-02-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0002_alter_example_project"),
        ("labels", "0005_alter_relation_project"),
        ("projects", "0002_auto_20220204_0201"),
        ("auto_labeling", "0004_alter_autolabelingconfig_project"),
        ("api", "0036_auto_20220204_0201"),
        ("label_types", "0003_auto_20220204_0201"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="ImageClassificationProject",
                ),
                migrations.DeleteModel(
                    name="IntentDetectionAndSlotFillingProject",
                ),
                migrations.DeleteModel(
                    name="Project",
                ),
                migrations.DeleteModel(
                    name="Seq2seqProject",
                ),
                migrations.DeleteModel(
                    name="SequenceLabelingProject",
                ),
                migrations.DeleteModel(
                    name="Speech2textProject",
                ),
                migrations.DeleteModel(
                    name="Tag",
                ),
                migrations.DeleteModel(
                    name="TextClassificationProject",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="ImageClassificationProject", table="projects_imageclassificationproject"
                ),
                migrations.AlterModelTable(
                    name="IntentDetectionAndSlotFillingProject", table="projects_intentdetectionandslotfillingproject"
                ),
                migrations.AlterModelTable(name="Project", table="projects_project"),
                migrations.AlterModelTable(name="Seq2seqProject", table="projects_seq2seqproject"),
                migrations.AlterModelTable(name="SequenceLabelingProject", table="projects_sequencelabelingproject"),
                migrations.AlterModelTable(name="Speech2textProject", table="projects_speech2textproject"),
                migrations.AlterModelTable(name="Tag", table="projects_tag"),
                migrations.AlterModelTable(
                    name="TextClassificationProject", table="projects_textclassificationproject"
                ),
            ],
        )
    ]
