# Generated by Django 4.0.2 on 2022-05-12 02:27

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("examples", "0006_alter_example_upload_name"),
        ("labels", "0012_add_uuid_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportedCategory",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labels.category",),
        ),
        migrations.CreateModel(
            name="ExportedExample",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("examples.example",),
        ),
        migrations.CreateModel(
            name="ExportedRelation",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labels.relation",),
        ),
        migrations.CreateModel(
            name="ExportedSpan",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labels.span",),
        ),
        migrations.CreateModel(
            name="ExportedText",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labels.textlabel",),
        ),
    ]
