# Generated by Django 4.0.4 on 2022-06-30 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0016_segmentation"),
        ("data_export", "0002_exportedboundingbox"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportedSegmentation",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labels.segmentation",),
        ),
    ]
