# Generated by Django 3.2.11 on 2022-01-27 02:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_auto_20220127_0032"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnnotationRelations",
            new_name="Relation",
        ),
    ]
