# Generated by Django 3.2.11 on 2022-01-28 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0001_initial"),
        ("labels", "0003_auto_20220127_0654"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="category",
                    name="example",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="categories", to="examples.example"
                    ),
                ),
                migrations.AlterField(
                    model_name="span",
                    name="example",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="spans", to="examples.example"
                    ),
                ),
                migrations.AlterField(
                    model_name="textlabel",
                    name="example",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="texts", to="examples.example"
                    ),
                ),
            ],
            database_operations=[],
        )
    ]
