# Generated by Django 4.0.2 on 2022-02-22 07:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("label_types", "0007_delete_relationtypeold"),
        ("examples", "0002_alter_example_project"),
        ("labels", "0009_delete_relationold"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RelationNew",
            new_name="Relation",
        ),
    ]
