# Generated by Django 4.0.4 on 2022-06-30 05:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0006_alter_example_upload_name"),
        ("label_types", "0007_delete_relationtypeold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("labels", "0015_create_boundingbox_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Segmentation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("prob", models.FloatField(default=0.0)),
                ("manual", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("points", models.JSONField(default=list)),
                (
                    "example",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="segmentations", to="examples.example"
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="label_types.categorytype"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
