# Generated by Django 4.1.1 on 2022-11-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0016_segmentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundingbox',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relation',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='span',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='textlabel',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
