# Generated by Django 4.0.2 on 2022-02-22 05:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("label_types", "0006_auto_20220222_0512"),
        ("projects", "0003_alter_project_polymorphic_ctype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("labels", "0005_alter_relation_project"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Relation",
            new_name="RelationOld",
        ),
    ]
