# Generated by Django 4.0.2 on 2022-05-12 02:27

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0011_remove_relation_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name="relation",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name="span",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name="textlabel",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
