# Generated by Django 4.2.15 on 2025-06-12 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_project_minpercentage"),
        ("labels", "0017_discrepancymessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discrepancymessage",
            name="example",
        ),
        migrations.AddField(
            model_name="discrepancymessage",
            name="project",
            field=models.ForeignKey(
                default=39,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discrepancy_messages",
                to="projects.project",
            ),
            preserve_default=False,
        ),
    ]
