# Generated by Django 4.2.15 on 2025-06-16 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0012_question_data_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VotingConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Nome da configuração de votação", max_length=200)),
                ("description", models.TextField(help_text="Descrição da votação")),
                (
                    "voting_method",
                    models.CharField(
                        choices=[
                            ("approve_only", "Apenas Aprovar"),
                            ("disapprove_only", "Apenas Reprovar"),
                            ("approve_disapprove", "Aprovar ou Reprovar"),
                        ],
                        default="approve_disapprove",
                        help_text="Método de votação permitido",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(help_text="Data de início da votação")),
                ("end_date", models.DateField(help_text="Data de fim da votação")),
                ("start_time", models.TimeField(help_text="Horário de início da votação")),
                ("end_time", models.TimeField(help_text="Horário de fim da votação")),
                (
                    "status",
                    models.CharField(
                        choices=[("configured", "Configurada"), ("active", "Ativa"), ("ended", "Encerrada")],
                        default="configured",
                        help_text="Status atual da votação",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voting_configurations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.CreateModel(
            name="AnnotationRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Nome da regra de anotação", max_length=200)),
                ("description", models.TextField(help_text="Descrição detalhada da regra")),
                ("order", models.PositiveIntegerField(default=0, help_text="Ordem de apresentação da regra")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "voting_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_rules",
                        to="voting.votingconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "unique_together": {("voting_configuration", "name")},
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "vote",
                    models.CharField(
                        choices=[("approve", "Aprovar"), ("disapprove", "Reprovar"), ("neutral", "Neutro")],
                        help_text="Voto do usuário na regra",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotation_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="voting.annotationrule"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("annotation_rule", "user")},
            },
        ),
    ]
