# Generated by Django 4.2.15 on 2025-04-02 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("annotations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disagreement",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dataset_item_id", models.IntegerField()),
                ("signature", models.CharField(db_index=True, max_length=64)),
                ("disagreement_details", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(default="open", max_length=20)),
                ("resolution_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("annotations", models.ManyToManyField(to="annotations.annotation")),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
