# Generated by Django 4.0.7 on 2022-10-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0006_alter_example_upload_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="example",
            name="score",
            field=models.FloatField(default=100),
        ),
    ]
