# Generated by Django 4.2.15 on 2025-06-08 07:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discussions", "0002_message"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Message",
            new_name="ChatMessage",
        ),
        migrations.AlterModelOptions(
            name="chatmessage",
            options={},
        ),
    ]
