# Generated by Django 4.2.15 on 2025-06-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0004_chatmessage_reply_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="reply_to",
        ),
    ]
