# Generated by Django 3.2.11 on 2022-01-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0003_auto_20220127_0654"),
        ("api", "0033_auto_20220127_0654"),
        ("label_types", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RelationTypes",
            new_name="RelationType",
        ),
    ]
