# Generated by Django 4.0.2 on 2022-02-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_polymorphic_ctype"),
        ("labels", "0005_alter_relation_project"),
        ("label_types", "0003_auto_20220204_0201"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RelationType",
            new_name="RelationTypeOld",
        ),
    ]
