# Generated by Django 4.0.2 on 2022-02-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0009_delete_relationold"),
        ("label_types", "0006_auto_20220222_0512"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RelationTypeOld",
        ),
    ]
