# Generated by Django 4.0.2 on 2022-05-17 23:01

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("label_types", "0007_delete_relationtypeold"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyLabelType",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("label_types.categorytype",),
        ),
    ]
