# Generated by Django 3.2.11 on 2022-02-04 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_auto_20220204_0201"),
        ("examples", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="example",
                    name="project",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="examples", to="projects.project"
                    ),
                ),
            ],
            database_operations=[],
        )
    ]
