# Generated by Django 4.0.2 on 2022-04-05 02:46

import django_drf_filepond.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0002_alter_example_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="example",
            name="filename",
            field=models.FileField(
                default=".",
                max_length=1024,
                storage=django_drf_filepond.models.FilePondLocalStoredStorage(),
                upload_to="",
            ),
        ),
    ]
