# Generated by Django 4.0.2 on 2022-04-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0005_auto_20220405_0252"),
    ]

    operations = [
        migrations.AlterField(
            model_name="example",
            name="upload_name",
            field=models.CharField(max_length=512),
        ),
    ]
