# Generated by Django 4.2.15 on 2025-03-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perspectives", "0002_perspective_subject_alter_perspective_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perspective",
            name="linkedAnnotations",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
