# Generated by Django 4.0.4 on 2022-07-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0006_alter_example_upload_name"),
        ("data_export", "0003_exportedsegmentation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportedComment",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("examples.comment",),
        ),
    ]
