# Generated by Django 2.1.7 on 2019-07-15 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_question_and_answer_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qandaannotation',
            old_name='text',
            new_name='response',
        ),
        migrations.AddField(
            model_name='qandaannotation',
            name='start_offset',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='qandaannotation',
            unique_together={('document', 'user', 'response', 'start_offset')},
        ),
        migrations.AddField(
            model_name='document',
            name='extra_text',
            field=models.TextField(blank=True)
        ),
    ]
