# Generated by Django 2.1.7 on 2019-10-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_collaborative_annotation'),
        ('api', '0004_roles'),
    ]

    operations = [
    ]
