# Generated by Django 3.2 on 2021-04-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tag'),
        ('api', '0010_auto_20210413_0249'),
    ]

    operations = [
    ]
