# Generated by Django 3.2.8 on 2022-01-13 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0002_rename_rolemapping_member"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Member",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="Member",
                    table="members_member",
                ),
            ],
        )
    ]
