# Generated by Django 3.2.11 on 2022-02-04 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_auto_20220204_0201"),
        ("label_types", "0002_rename_relationtypes_relationtype"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="categorytype",
                    name="project",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.project"),
                ),
                migrations.AlterField(
                    model_name="relationtype",
                    name="project",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relation_types",
                        to="projects.project",
                    ),
                ),
                migrations.AlterField(
                    model_name="spantype",
                    name="project",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.project"),
                ),
            ],
            database_operations=[],
        )
    ]
