# Generated by Django 4.1.1 on 2022-10-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("label_types", "0007_delete_relationtypeold"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorytype",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="relationtype",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="spantype",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
