# Generated by Django 4.0.4 on 2022-06-30 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_boundingboxproject_alter_project_project_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentationProject",
            fields=[
                (
                    "project_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("projects.project",),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("DocumentClassification", "document classification"),
                    ("SequenceLabeling", "sequence labeling"),
                    ("Seq2seq", "sequence to sequence"),
                    ("IntentDetectionAndSlotFilling", "intent detection and slot filling"),
                    ("Speech2text", "speech to text"),
                    ("ImageClassification", "image classification"),
                    ("BoundingBox", "bounding box"),
                    ("Segmentation", "segmentation"),
                ],
                max_length=30,
            ),
        ),
    ]
