# Generated by Django 4.1.7 on 2023-06-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_imagecaptioningproject_alter_project_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="allow_member_to_create_label_type",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("DocumentClassification", "Document Classification"),
                    ("SequenceLabeling", "Sequence Labeling"),
                    ("Seq2seq", "Seq2Seq"),
                    ("IntentDetectionAndSlotFilling", "Intent Detection And Slot Filling"),
                    ("Speech2text", "Speech2Text"),
                    ("ImageClassification", "Image Classification"),
                    ("BoundingBox", "Bounding Box"),
                    ("Segmentation", "Segmentation"),
                    ("ImageCaptioning", "Image Captioning"),
                ],
                max_length=30,
            ),
        ),
    ]
