# Generated by Django 4.2.15 on 2025-03-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_optionsgroup_perspective_questiontype_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questiontype",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
